@startuml
'https://plantuml.com/class-diagram

class Main
class Bundesliga
class Game
class Team
class TeamScore

Bundesliga "1"-->"1" Team
Bundesliga --> LeagueTable
Bundesliga --> Game
Team "1"-->"n" Player
Team "1"-->"1" TeamScore
TeamScore "n"<--"1" LeagueTable
'LeagueTable "1"<--"n" TeamScore
Player "1"-->"n" PlayerPosition
Game "1"-->"2" TeamScore
Main --> Bundesliga
LeagueTable --> Matchday
Matchday --> Game

class Game {
var Dauer
size()
start()
}




@enduml